# Odoo yaml template for travis-ci
# __version__=0.2.2.13
# Can used both in local travis emulator both in travis environment
# Notice: in local travis emulator macroes are substituted at 2 layers:
# - format: ${macro} are replaced before execution (at travis.yml read)
# - format: $macro are replace by shell during execution

language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"

virtualenv:
  system_site_packages: true

git:
  submodules: false
  depth: false

addons:
  apt:
    sources:
#      - pov-wkhtmltopdf
#    Search your sources alias here:
#      https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    packages:
      - shellcheck
#     Search your packages here:
#       https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
#     For wkhtmltopdf, see the env section below

before_install:
  # Tools are used to test themselves packages
  - ln -s ${TRAVIS_BUILD_DIR} ${HOME}
  - cp -R ${TRAVIS_BUILD_DIR}/maintainer-quality-tools ${HOME}
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - export PATH=${HOME}/maintainer-quality-tools/_travis:${PATH}
  # - export OPTS="-j"

install:
  - travis_install_env tools

env:
  global:
  - TRAVIS_DEBUG_MODE="1"
  - TESTS="0" LINT_CHECK="0" BASH_CHECK="0" LINT_CHECK_LEVEL="MINIMAL"

  matrix:
  - LINT_CHECK="1" BASH_CHECK="0" TESTS="1" MODULE_PATH=${TRAVIS_BUILD_DIR}/z0lib PYTHONPATH=${MODULE_PATH}
  - LINT_CHECK="0" BASH_CHECK="0" TESTS="1" MODULE_PATH=${TRAVIS_BUILD_DIR}/clodoo PYTHONPATH=${MODULE_PATH}
  # - LINT_CHECK="1" BASH_CHECK="0" TESTS="1" MODULE_PATH=${TRAVIS_BUILD_DIR}/travis_emulator PYTHONPATH=${MODULE_PATH}
  - LINT_CHECK="0" BASH_CHECK="0" TESTS="1" MODULE_PATH=${TRAVIS_BUILD_DIR}/zar PYTHONPATH=${MODULE_PATH}
  - LINT_CHECK="0" BASH_CHECK="0" TESTS="1" MODULE_PATH=${TRAVIS_BUILD_DIR}/zerobug PYTHONPATH=${MODULE_PATH}

script:
  - cd $MODULE_PATH; pwd
  - travis_run_pypi_tests ${OPTS}

after_success:
  - cd PYTHONPATH=${MODULE_PATH}; travis_after_tests_success ${OPTS}
