# Config file travis.yml for no Odoo package test
# version 0.1.4

language: python
sudo: false

python:
  - "2.7"

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      # - python-serial
      # - python-yaml

before_install:
  - PYTHONPATH=${PKGPATH}

env:
  global:
  - TESTS="0" LINT_CHECK="0" BASH_CHECK="0" TRANSIFEX="0"

  matrix:
  - LINT_CHECK="1" BASH_CHECK="1" TESTS="1" PRJNAME="zerobug"
  - LINT_CHECK="1" BASH_CHECK="1" TESTS="1" PRJNAME="zar"

virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/zeroincombenze/tools.git
  - export PATH=${HOME}/tools/travis_emulator/_travis:${PATH}

script:
  - cd $PKGPATH/$PRJNAME; travis_run_tests -r

after_success:
  - cd $PKGPATH/zerobug; travis_after_tests_success
  - cd $PKGPATH/zar; travis_after_tests_success
  - cd $PKGPATH; travis_after_tests_success zerobug,zar
