# Config file .travis.yml

sudo: required
language: python

python:
  - "2.7"

env:
  matrix:
  - DEV_ENVIRONMENT="pytok" PYTOK_VERSION="0.2" TESTS="0" LINT_CHECK="0"

virtualenv:
   system_site_packages: true

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install coveralls

script:
  - travis_run_tests
  - cd ./pytok/; make travis

after_success:
  coveralls

