# Odoo yaml template for travis-ci
# __version__=0.2.2.35

language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  # For branches <= 10.0, put `- "2.7.13"`
  - "3.5"

virtualenv:
  system_site_packages: true

git:
  submodules: false

services:
  - postgresql

addons:
  # By default postgresql-9.1 is installed but there is issue related:
  #  https://github.com/OCA/maintainer-quality-tools/issues/432#issuecomment-281580935
  # Better use higher PostgreSQL version
  postgresql: "9.5"
  apt:
    sources:
#   Search your sources alias here:
#     https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
      - pov-wkhtmltopdf
    packages:
#   Search your packages here:
#     https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
      - expect-dev  # provides unbuffer utility
      - python-lxml


before_install:
# Sometimes complicated website repos need Compass & SaSS:
#  - rvm install ruby --latest
#  - gem install bootstrap-sass
#  - gem install compass --pre
  - export TRAVIS_DEBUG_MODE="1"
  - pip install urllib3[secure] --upgrade; true
  - git clone https://github.com/zeroincombenze/tools.git ${HOME}/tools --depth=1
  - mv ${HOME}/tools/maintainer-quality-tools ${HOME}
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}

install:
  - travis_install_env
  - export EXCLUDE=hw_scanner,hw_escpos,document_ftp,delivery,stock_invoice_directly,claim_from_delivery
  - export INCLUDE=$(getaddons.py -m ${HOME}/build/${ODOO_REPO}/odoo/addons ${HOME}/build/${ODOO_REPO}/addons)

env:
  global:
  - VERSION="$TRAVIS_BRANCH" TESTS="0" LINT_CHECK="0"  MAKEPOT="0" TRANSIFEX="0" ODOO_REPO="$TRAVIS_REPO_SLUG"
  # Set this variable to some version existing as linux-generic build on
  # https://github.com/wkhtmltopdf/wkhtmltopdf/releases
  # if you need to install wkhtmltopdf
  # - WKHTMLTOPDF_VERSION="0.12.4"
  # Set the above to install a `wkhtmltopdf` version that is not the one provided
  # by the `pov-wkhtmltopdf` repo.
  - PHANTOMJS_VERSION="latest"
  # The above line controls the PhantomJS version that is used for JS testing.
  #   It is not necessary to include this value unless you are altering the default.
  #   Use `OS` to skip the PhantomJS upgrade & use the system version instead.
  - WEBSITE_REPO="1"
  # Use the above line to install dependencies that are required for website repos:
  # * SASS & Bootstrap-SASS
  # * Compass

  matrix:
  - LINT_CHECK="1"
# use this to install a standalone database to export .pot files
# - MAKEPOT="1"
# add MAKEPOT="1" to a TEST line to export .pot files from
# the test database after test success
  - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="1"
  - TESTS="1" ODOO_REPO="OCA/OCB"
  - TESTS="1" ODOO_REPO="zeroincombenze/OCB"
# either use the two lines above or the two below. Don't change the default if
# it's not necessary (it is only necessary if modules in your repository can't
# be installed in the same database. And you get a huge speed penalty in your
# tests)
#  - TESTS="1.0" ODOO_REPO="odoo/odoo" UNIT_TEST="1"
#  - TESTS="1.0" ODOO_REPO="OCA/OCB" UNIT_TEST="1"
#  - TESTS="1.0" ODOO_REPO="zeroincombenze/OCB" UNIT_TEST="1"

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
