-
  - '^# -\*- coding: utf-8 -\*-'
  -
    - '$'
    - matches_utf8
-
  - '^#!'
  -
    - '$'
    - matches_ignore
-
  - '^# (flake8|pylint):'
  -
    - '$'
    - matches_lint
-
  - '!(coding|flake8|pylint|python|/bin/env)^#'
  -
    - '$'
    - matches_no_lint
-
  - '^ *class [^(]+\('
  -
    - '$'
    - matches_class
-
  - '^# -\*- encoding: utf-8 -\*-'
  -
    - 'd'
