include_odoo_py_new_api:
  ctx: 'final or migrate_multi'
  include: 'odoo_py_new_api'
include_odoo_api_multi:
  ctx: 'final'
  include: 'odoo_py_api_multi'
product_uom:
  match: '["'']uom\.uom["'']'
  prio: '9'
  do:
    - action: 's'
      args:
      - 'uom.uom'
      - 'product.uom'
product_uom_categ_unit:
  match: '["'']uom\.product_uom_categ_unit["'']'
  prio: '9'
  do:
    - action: 's'
      args:
      - 'uom.product_uom_categ_unit'
      - 'product.product_uom_categ_unit'
